version: "3.8"

services:
  database:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: SO_RH
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports:
      - 7777:8080

  apps:
    image: projetsorh:latest 
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/SO_RH

volumes:
  db:
